/*
 * cfg.c
 *
 * Created: 1/1/2025 2:08:43 PM
 *  Author: yaraa
 */ 
/*
	MDIO_OUTPUT,
	MDIO_INPUT_PULLUP,
	MDIO_INPUT_PULLDOWN,
*/
#include "../../STD_TYPES.h"
#include "../../BIT_MATH.h"
#include "MDIO.h"
#include "../MPORT/MPORT.h"
#include "cfg.h"
u8 PinCfg [32]={
	MDIO_INPUT_PULLDOWN,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLUP,
	MDIO_INPUT_PULLUP,
	MDIO_INPUT_PULLDOWN,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLUP,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLDOWN,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLDOWN,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLUP,
	MDIO_OUTPUT,
	MDIO_INPUT_PULLDOWN,
	MDIO_INPUT_PULLUP,
	MDIO_INPUT_PULLUP,
	MDIO_OUTPUT,
	MDIO_OUTPUT,
	MDIO_OUTPUT
};
u8 PinCfg2[32][2] = {
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PA0
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PA1
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PA2
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PA3 - Button
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PA4 - Button
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PA5 - Button
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PA6
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PA7
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PB0
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PB1
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PB2
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PB3
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLDOWN},  // PB4
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PB5
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PB6
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PB7
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC0
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC1
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC2
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLDOWN},  // PC3
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC4
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLDOWN},  // PC5
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC6
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PC7
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PD0
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PD1
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLDOWN},  // PD2
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PD3
	{MPORT_INPUT, PORT_PIN_MODE_INPUT_PULLUP},    // PD4
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PD5
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE},        // PD6
	{MPORT_OUTPUT, PORT_PIN_MODE_NO_MODE}         // PD7
};
